In [ ]:
from sklearn.datasets import fetch_california_housing

# Load the California housing dataset
housing = fetch_california_housing(as_frame=True)
X = housing.data
y = housing.target

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
import numpy as np

# Model 1: Linear Regression
linear_reg = LinearRegression()
linear_reg.fit(X_train, y_train)
y_pred_lr = linear_reg.predict(X_test)

r2_lr = r2_score(y_test, y_pred_lr)
rmse_lr = np.sqrt(mean_squared_error(y_test, y_pred_lr))

print(f"Linear Regression R2 Score: {r2_lr:.4f}")
print(f"Linear Regression RMSE: {rmse_lr:.4f}")

Linear Regression R2 Score: 0.5966
Linear Regression RMSE: 0.7274


In [ ]:
from sklearn.ensemble import AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor

# Model 2: AdaBoost Regressor
adaboost_reg = AdaBoostRegressor(random_state=1)
adaboost_reg.fit(X_train, y_train)
y_pred_abr = adaboost_reg.predict(X_test)

r2_abr = r2_score(y_test, y_pred_abr)
rmse_abr = np.sqrt(mean_squared_error(y_test, y_pred_abr))

print(f"AdaBoost Regressor R2 Score: {r2_abr:.4f}")
print(f"AdaBoost Regressor RMSE: {rmse_abr:.4f}")

AdaBoost Regressor R2 Score: 0.3945
AdaBoost Regressor RMSE: 0.8912


In [ ]:
from sklearn.tree import DecisionTreeRegressor

# Model 3: Decision Tree Regressor
decision_tree_reg = DecisionTreeRegressor(random_state=1)
decision_tree_reg.fit(X_train, y_train)
y_pred_dtr = decision_tree_reg.predict(X_test)

r2_dtr = r2_score(y_test, y_pred_dtr)
rmse_dtr = np.sqrt(mean_squared_error(y_test, y_pred_dtr))

print(f"Decision Tree Regressor R2 Score: {r2_dtr:.4f}")
print(f"Decision Tree Regressor RMSE: {rmse_dtr:.4f}")

Decision Tree Regressor R2 Score: 0.6179
Decision Tree Regressor RMSE: 0.7080


In [ ]:
from sklearn.datasets import load_iris

# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)

In [ ]:
from sklearn.linear_model import LogisticRegression

# Train the Logistic Regression model
logistic_reg = LogisticRegression(random_state=1, max_iter=200) # Increased max_iter for convergence
logistic_reg.fit(X_train, y_train)

# Make predictions on the test data
y_pred = logistic_reg.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

# Print the confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Print the classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=iris.target_names))

Confusion Matrix:
[[17  0  0]
 [ 0 18  1]
 [ 0  0 14]]

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        17
  versicolor       1.00      0.95      0.97        19
   virginica       0.93      1.00      0.97        14

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



In [ ]:
# setosa= class 0, versicolor= class 1,  virginica =class2

In [ ]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer

# Load the train subset of '20newsgroups' data
newsgroups = fetch_20newsgroups(subset='train', return_X_y=True)
X_text, y = newsgroups

# Vectorize X using TfidfVectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(X_text)

print("Shape of vectorized data X:", X.shape)
print("Shape of target y:", y.shape)

Shape of vectorized data X: (11314, 130107)
Shape of target y: (11314,)


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

# Split the vectorized data into training and validation sets
X_train_text, X_val_text, y_train_text, y_val_text = train_test_split(X, y, test_size=0.3, random_state=1)

# Train a Multinomial Naive Bayes model
mnb = MultinomialNB()
mnb.fit(X_train_text, y_train_text)

# Compute the score on the validation set
score = mnb.score(X_val_text, y_val_text)

print(f"MultinomialNB validation score: {score:.4f}")

MultinomialNB validation score: 0.8274
